### ISSUE TITLE
Creating docker-compose for discord bot

### ISSUE THREAD

**Issue by kapselccc** [esoviscode/discord-bot#37]

**Comment by Marsh-sudo** [comment]
Would like to try it out :)

**Comment by Silentsky0** [comment]
Sure, the instructions to set up the development environment are listed in the main README. If you may have any questions or problem feel free to ask them here, I'll be happy to help :)

**Comment by Marsh-sudo** [comment]
Am getting an error when am trying to run the programme...Here it is

File "/app/dnd_bot/dc/init.py", line 34, in bot_run
    raise KeyError(f'Failed to get configuration key. Env name: {env_token}')
KeyError: 'Failed to get configuration key. Env name: BOT_TOKEN'

Seems to me the problem is the BOT_TOKEN you hide and how you wanted it to be expressed through the .env file it isn't working

**Comment by Silentsky0** [comment]
Yep, this is a bot token generated by the Discord API, which is used to authenticate the bot as a discord user. We cannot give it to you unfortunately.

I found a guide to create this token, so you can set up another bot account  and run it.
https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
